runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
    - run: pnpm install --frozen-lockfile
      shell: bash
    - name: 'TL codegen'
      run: pnpm -C packages/tl run gen-code
      shell: bash