name: Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    if: github.repository == 'mtcute/mtcute' # do not run on forks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: pnpm install --frozen-lockfile
      - name: 'TL codegen'
        run: pnpm -C packages/tl run gen-code
      - name: Build
        run: pnpm run -r build
      - name: Build docs
        run: |
          pnpm run docs 
          touch docs/.nojekyll
          echo "ref.mtcute.dev" > docs/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
